POST http://localhost:3000/api/users HTTP/1.1
content-Type: application/json

{
    "email":"jose.aceves@gmail.com",
    "password":"Jose123",
    "username":"joseA"
}

###
PUT http://localhost:3000/api/login
content-Type: application/json

{
    "password":"Jose123",
    "username":"joseA"
}

###
GET http://localhost:3000/api/users
x-auth-user: MP3D9lJfLC-6382aabe652642d0dc4a9578

###
GET http://localhost:3000/api/users/bestScores
x-auth-user: MP3D9lJfLC-6382aabe652642d0dc4a9578

###
GET http://localhost:3000/api/users/saveGames
x-auth-user: MP3D9lJfLC-6382aabe652642d0dc4a9578

###
GET http://localhost:3000/api/users/leaders
x-auth-user: MP3D9lJfLC-6382aabe652642d0dc4a9578

###
GET http://localhost:3000/api/users/saveGames?index=0
x-auth-user: MP3D9lJfLC-6382aabe652642d0dc4a9578

###
GET http://localhost:3000/api/users/bestScores?index=0
x-auth-user: MP3D9lJfLC-6382aabe652642d0dc4a9578


    # "email":"jose.aceves@gmail.com",
    # "password":"Jose123",
    # "username":"joseA"
    # MP3D9lJfLC-6382aabe652642d0dc4a9578

    # "email":"HectorAinferno@gmail.com",
    # "password":"hectorin123A",
    # "username":"hectorininferno"
    # un0izBMs9k-6382aaecbd62980b0e36459c